---
title: "FGF Nuclei Neuron Prep"
output: html_notebook
---

#Load Libraries
```{r, message=F, warning=FALSE}
library(Seurat)
library(tidyverse)
library(DESeq2)
library(here)
library(future)
library(cluster)
library(parallelDist)
library(ggplot2)
library(cowplot)
library(ggrepel)
library(future.apply)
library(reshape2)
library(gProfileR)
library(ggsignif)
plan("multiprocess", workers = 40)
options(future.globals.maxSize = 4000 * 1024^2)
```

# Set chunk options
```{r include = FALSE}
knitr::opts_chunk$set(message = FALSE, warnings = FALSE)
source(here("code/sc_functions.R"))
```

# Load prepped data
```{r load neurons, fig.width=10, fig.height=4}
# seur.sub <- readRDS(here("data/fgf_filtered_nuclei.RDS"))
# ```
# 
# # Food Intake and BG of mice
# ```{r FI_BG}
# #Read in excel file of FI
# fi_v <- readxl::read_xlsx(here("data/mouse_data/fig1/191120_FIBG.xlsx"), range = "C7:N24")
# colnames(fi_v) <- c(paste0("V_D", seq_len(6)), paste0("F_D", seq_len(6)))
# melt(fi_v, id.vars = NULL) %>%
#   na.omit() %>%
#   mutate(value = as.numeric(value)) %>%
#   dplyr::group_by(variable) %>%
#   dplyr::summarise(
#     mean = mean(value, na.rm = T),
#     sd = sd(value, na.rm = T),
#     se = sd / sqrt(length(variable))
#   ) %>%
#   mutate(day = rep(c(0:5), 2)) %>%
#   separate(variable, sep = "_", into = "trt") %>%
#   ggplot(aes(x = day, y = mean, color = trt)) + geom_point(size = 1) + 
#   geom_line(size = 1) +
#   geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = .2) + 
#   ggpubr::theme_pubr() +
#   scale_color_manual(name = NULL, labels = c(expression(icv ~ hFGF1 ~ 3 * mu * g), "icv Vehicle pair-fed"), 
#                      values = c("gray30", "gray80")) +
#   scale_x_continuous(breaks = c(0, 1, 2, 3, 4, 5)) +
#   ylab("Daily food intake (g)") + 
#   xlab("Days") + ylim(c(0, 10)) +
#   theme(legend.position = "none", legend.background = element_blank()) + 
#   theme_figure -> fi_fig1
# 
# #Read in excel file of BG
# bg <- readxl::read_xlsx(here("data/mouse_data/fig1/191120_FIBG.xlsx"), range = "B27:O44")
# colnames(bg) <- c(paste0("V_D", seq_len(7)), paste0("F_D", seq_len(7)))
# melt(bg, id.vars = NULL) %>%
#   na.omit() %>%
#   mutate(value = as.numeric(value)) %>%
#   dplyr::group_by(variable) %>%
#   dplyr::summarise(
#     mean = mean(value, na.rm = T),
#     sd = sd(value, na.rm = T),
#     se = sd / sqrt(length(variable))
#   ) %>%
#   mutate(day = rep(c(0:6), 2)) %>%
#   separate(variable, sep = "_", into = "trt") %>%
#   ggplot(aes(x = day, y = mean, color = trt)) + 
#   geom_point(size = 1) + geom_line(size = 1) +
#   geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = .2) + 
#   ggpubr::theme_pubr() +
#   scale_color_manual(name = NULL, labels = c(expression(icv ~ hFGF1 ~ 3 * mu * g), 
#                                              "icv Vehicle pair-fed"), values = c("gray30", "gray80")) +
#   scale_x_continuous(breaks = c(0, 1, 2, 3, 4, 5, 6),
#     label = c("Pre", "0", "1", "2", "3", "4", "5")) +
#   ylab("BG levels (mg/dl)") + xlab("Days") +
#   theme(legend.direction = "vertical", legend.position = "none", legend.background = element_blank()) + 
#   theme_figure -> bg_fig1
# 
# blank <- plot_grid("")
# bg_fi <- plot_grid(fi_fig1, bg_fig1)
# ```
# 
# # Publication figures of clustering (all nuclei)
# ```{r fig1 panel b}
# seur.sub <- RenameIdents(seur.sub, "Agrp" = "Neuron")
# seur.sub <- RenameIdents(seur.sub, "Hist" = "Neuron")
# seur.sub <- RenameIdents(seur.sub, "Neur" = "Neuron")
# seur.sub <- RenameIdents(seur.sub, "Glia" = "Astro/Tany/Epend")
# seur.sub <- RenameIdents(seur.sub, "COP" = "OPC/COP")
# seur.sub <- RenameIdents(seur.sub, "Endo" = "Endothelial")
# seur.sub <- RenameIdents(seur.sub, "Micro" = "Microglia")
# 
# data.frame(Embeddings(seur.sub, reduction = "umap")) %>% 
#   mutate(group = seur.sub$group) %>%
#   mutate(celltype = Idents(seur.sub)) %>%
#   .[sample(nrow(.)),] %>% 
#   mutate(group = replace(group, group == "FGF_Day-5", "FGF_d5")) %>% 
#   mutate(group = replace(group, group == "FGF_Day-1", "FGF_d1")) %>% 
#   mutate(group = replace(group, group == "PF_Day-1", "Veh_d1")) %>%
#   mutate(group = replace(group, group == "PF_Day-5", "Veh_d5")) -> umap_embed
# 
# label.df <- data.frame(cluster=levels(umap_embed$celltype),label=levels(umap_embed$celltype))
# label.df_2 <- umap_embed %>% 
#   dplyr::group_by(celltype) %>% 
#   dplyr::summarize(x = median(UMAP_1), y = median(UMAP_2)) 
# 
# prop_seur_byclus <- ggplot(umap_embed, aes(x=UMAP_1, y=UMAP_2, color=celltype)) + 
#   geom_point(size=1, alpha=0.5)  + 
#   geom_text_repel(data = label.df_2, aes(label = celltype, x=x, y=y), 
#                   size=3, fontface="bold", inherit.aes = F, bg.colour="white") +
#   xlab("UMAP1") + ylab("UMAP2") +
#   ggpubr::theme_pubr() + ggsci::scale_color_igv() + theme_figure + theme(legend.position = "none", legend.title=NULL)
# 
# prop_seur_group <- ggplot(umap_embed, aes(x=UMAP_1, y=UMAP_2, color=group)) + 
#   geom_point(size=1, alpha=0.5)  + guides(color = guide_legend(override.aes = list(size = 3))) +
#   ggpubr::theme_pubr() + ggsci::scale_color_jco(name = "Treatment Group") +
#   xlab("UMAP1") + ylab("UMAP2") +
#   theme_figure + theme(legend.position = c(.9,.3), legend.title = element_blank(), 
#                        legend.text = element_text(size=12, face="bold"))
# plot_grid(prop_seur_group, prop_seur_byclus)
# ```
# 
# ```{r recluster neurons, fig.width=10, fig.height=4}
# subset(seur.sub, ident="Neuron") %>% 
#   reprocess_subset(., dims = 30, resolution = 0.1) -> fgf.neur
# DimPlot(fgf.neur, label = T)
# ```
# 
# # Load Datasets
# ```{r load mapping datasets}
# load("/projects/mludwig/Dataset_alignment/Data_preprocessing/Campbell_neurons_preprocessed.RData")
# campbell <- UpdateSeuratObject(campbell)
# Idents(campbell) <- "cell_type"
# subset(campbell, idents = c("n34.unassigned(2)", "n33.unassigned(1)"), invert = T) %>%
#   NormalizeData(verbose = FALSE) %>%
#   FindVariableFeatures(
#     selection.method = "vst",
#     nfeatures = 2000, verbose = FALSE
#   ) %>%
#   ScaleData(verbose = FALSE) %>%
#   RunPCA(npcs = 30, verbose = FALSE) -> campbell
# 
# # Load Chen Data
# load("/projects/mludwig/Dataset_alignment/Data_preprocessing/Chen_neurons_preprocessed.RData")
# chen <- UpdateSeuratObject(chen)
# Idents(chen) <- "cell_type"
# chen %>%
#   NormalizeData(verbose = FALSE) %>%
#   FindVariableFeatures(
#     selection.method = "vst",
#     nfeatures = 2000, verbose = FALSE
#   ) %>%
#   ScaleData(verbose = FALSE) %>%
#   RunPCA(npcs = 30, verbose = FALSE) -> chen
# 
# # Load Romanov Data
# load("/projects/mludwig/Dataset_alignment/Data_preprocessing/Romanov_neurons_preprocessed.RData")
# romanov <- UpdateSeuratObject(romanov)
# Idents(romanov) <- "cell_type"
# romanov %>%
#   NormalizeData(verbose = FALSE) %>%
#   FindVariableFeatures(
#     selection.method = "vst",
#     nfeatures = 2000, verbose = FALSE
#   ) %>%
#   ScaleData(verbose = FALSE) %>%
#   RunPCA(npcs = 30, verbose = FALSE) -> romanov
# ```
# 
# #Propagate Labels
# ```{r iterative label propagation, warning=FALSE, message=FALSE}
# #propagate Campbell labels
# fgf.neur <- prop_function(reference = campbell, query = fgf.neur)
# hist(fgf.neur$pred_CONF)
# fgf.neur.camp <- subset(fgf.neur, pred_CONF > 0.75)
# 
# #propagate Chen labels
# subset(fgf.neur, pred_CONF < 0.75) %>%
#   FindVariableFeatures(selection.method = "vst", nfeatures = 2000, verbose = FALSE) %>%
#   prop_function(reference = chen, query = .) -> fgf.neur.relab_chen
# hist(fgf.neur.relab_chen$pred_CONF)
# fgf.neur.chen <- subset(fgf.neur.relab_chen, pred_CONF > 0.75)
# 
# #propagate Romanov labels
# subset(fgf.neur.relab_chen, pred_CONF < 0.75) %>%
#   FindVariableFeatures(selection.method = "vst", nfeatures = 2000, verbose = FALSE) %>%
#   prop_function(reference = romanov, query = .) -> fgf.neur.relab_rom
# hist(fgf.neur.relab_rom$pred_CONF)
# fgf.neur.rom <- subset(fgf.neur.relab_rom, pred_CONF > 0.75)
# 
# #transfer labels to fgf object
# prop_lab <- data.frame(
#   cell.names = c(colnames(fgf.neur.camp), colnames(fgf.neur.chen), colnames(fgf.neur.rom)),
#   labels = c(fgf.neur.camp$pred_ID, fgf.neur.chen$pred_ID, fgf.neur.rom$pred_ID))
# fgf.neur$ref <- as.character(prop_lab[match(colnames(fgf.neur), prop_lab$cell.names), "labels"])
# fgf.neur$ref[is.na(fgf.neur$ref)] <- "unmap"
# 
# #save object with labels
# saveRDS(fgf.neur, file = here("data/neuron/fgf_neur_mappingscores.RDS"))
# ```
# 
# #Filter and recluster dataset
# ```{r reclustering of mapped neurons}
# fgf.neur.prop <- subset(fgf.neur, ref != "unmap")
# fgf.neur.prop <- reprocess_subset(fgf.neur.prop, dims = 30, resolution = 0.1)
# DefaultAssay(fgf.neur.prop) <- "SCT"
# lab.mark <- FindAllMarkers(fgf.neur.prop, only.pos = T, logfc.threshold = 0.5)
# table(fgf.neur.prop@active.ident, fgf.neur.prop$ref) %>%
#   as.data.frame() %>%
#   group_by(Var1) %>%
#   top_n(1, Freq) %>%
#   select(Var1, Var2) -> label_mapping
# lab.mark$prop_label <- as.character(pull(label_mapping[match(lab.mark$cluster, label_mapping$Var1), "Var2"]))
# write_csv(x = lab.mark, here("neuron_clusters.csv"))
# ```
# 
# #Rename clusters
# ```{r find specific markers for both Glu5 populations}
# rename <- c("Hcrt (Chen_Glu12)","Tcf7l2 (Chen_Glu4)","Grm7/Foxb1 (Chen_Glu5)","Nxph1/Foxb1 (Chen_Glu5)",
#             "Tac1/Htr2c (Chen_Glu6)","Hist (Camp_n1)","Tac1/Gad2 (Camp_n2)", 
#             "Avp/Oxt (Camp_n6)","Agrp (Camp_n13)",
#             "Vip (Camp_n16)","Tac2 (Camp_n20)","Sst (Camp_n23)","Hs3st4/Nr5a1 (Camp_n29)",
#             "Fam19a2 (Camp_n31)","Pmch (Roma_Pmch)")
# rename <- rename
# names(rename) <- as.character(label_mapping$Var1)
# ```
# 
# 
# # Neuron specific clustering
# ```{r fig1 panel c}
# fgf.neur.prop[["recluster_0.1"]] <- Idents(object = fgf.neur.prop)
# fgf.neur.prop <- RenameIdents(fgf.neur.prop, rename)
# 
# data.frame(Embeddings(fgf.neur.prop, reduction = "umap")) %>% 
#   mutate(group = fgf.neur.prop$group) %>%
#   mutate(celltype = Idents(fgf.neur.prop)) %>%
#   sample_frac(1L) -> umap_embed
# colnames(umap_embed)[1:2] <- c("UMAP 1", "UMAP 2")
# 
# label.df <- data.frame(cluster=levels(umap_embed$celltype),label=levels(umap_embed$celltype))
# label.df_2 <- umap_embed %>% 
#   group_by(celltype) %>% 
#   dplyr::summarize(x = median(`UMAP 1`), y = median(`UMAP 2`)) 
# 
# prop_neur_byclus <- ggplot(umap_embed, aes(x=`UMAP 1`, y=`UMAP 2`, color=celltype)) + 
#   geom_point(size=0.5, alpha=0.5)  + 
#   geom_text_repel(data = label.df_2, aes(label = celltype, x=x, y=y), 
#                   size=2, 
#                   inherit.aes = F, bg.colour="white", fontface="bold",
#                   force=1, min.segment.length = unit(0, 'lines')) +
#   xlab("UMAP1") + ylab("UMAP2") +
#   ggpubr::theme_pubr(legend="none") + ggsci::scale_color_igv() + theme_figure 
# ```
# 
# #Extract color scheme
# ```{r}
# g <- ggplot_build(prop_neur_byclus)
# cols<-data.frame(colours = as.character(unique(g$data[[1]]$colour)), 
#              label = as.character(unique(g$plot$data[, g$plot$labels$colour])))
# colvec<-as.character(cols$colours)
# names(colvec)<-as.character(cols$label)
# ```
# 
# #Resampling DEG
# ```{r pseudobulk resampling, message=F, warning=FALSE}
# #Generate matrices
# split_mats<-splitbysamp(fgf.neur.prop, split_by="sample")
# names(split_mats)<-unique(Idents(fgf.neur.prop))
# pb<-replicate(100, gen_pseudo_counts(split_mats, ncells=10)) 
# names(pb)<-paste0(rep(names(split_mats)),"_",rep(1:100, each=length(names(split_mats))))
# 
# # Generate DESeq2 Objects
# res<-rundeseq(pb)
# ```
# 
# # Identify neuronal populations with most DE genes at 24 hr
# ```{r plot resampling, message=F, warning=FALSE}
# degenes<-lapply(res, function(x) {
#   tryCatch({
#     y<-x[[2]]
#     y<-na.omit(y)
#     data.frame(y)%>%filter(padj<0.1)%>%nrow()}, 
#     error=function(err) {NA})
# })
# 
# boxplot<-lapply(unique(Idents(fgf.neur.prop)), function(x) {
#   z<-unlist(degenes[grep(as.character(x), names(degenes), fixed = T)])
# })
# 
# names(boxplot)<-unique(Idents(fgf.neur.prop))
# boxplot<-t(as.data.frame(do.call(rbind, boxplot)))
# rownames(boxplot)<-1:100
# genenum<-melt(boxplot)
# write_csv(genenum, path = here("output/neuron/genenum.csv"))
```

#Figure 1 Panel C
```{fig 1 panel c}
genenum <- read_csv(here("output/neuron/genenum.csv"))
ggplot(genenum,aes(x=reorder(Var2, -value), y=value, fill=factor(Var2))) + 
  geom_boxplot(notch = T, alpha=0.75) + 
  #scale_fill_manual(values = colvec) +
  ggpubr::theme_pubr() +
  theme(axis.text.x = element_text(angle=45, hjust=1), legend.position = "none") + 
  ylab("Number DEG") + xlab(NULL) + theme_figure

#deboxplot
```

<!-- #Specific Agrp analysis -->
<!-- ```{r, message=F, warning=FALSE} -->
<!-- agrp<-subset(fgf.neur.prop, ident="Agrp (Camp_n13)") -->
<!-- agrp %>% ScaleData(verbose=F) %>%  -->
<!--   FindVariableFeatures(selection.method = "vst",  -->
<!--                        nfeatures = 2000) %>% -->
<!--   RunPCA(ndims.print=1:10) -> agrp -->

<!-- list_sub <- SplitObject(agrp, split.by="sample") -->
<!-- pb <- (lapply(list_sub, function(y) { -->
<!--     DefaultAssay(y) <- "SCT" -->
<!--     mat<-GetAssayData(y, slot="counts") -->
<!--     counts <- Matrix::rowSums(mat) -->
<!-- }) %>% do.call(rbind, .) %>% t() %>% as.data.frame()) -->

<!-- trt<-ifelse(grepl("FGF", colnames(pb)), yes="F", no="P") -->
<!-- batch<-as.factor(sapply(strsplit(colnames(pb),"_"),"[",1)) -->
<!-- day<-ifelse(as.numeric(as.character(batch))>10, yes="Day-5", no="Day-1") -->
<!-- group<-paste0(trt,"_",day) -->
<!-- meta<-data.frame(trt=trt, day=factor(day), group=group) -->
<!-- dds <- DESeqDataSetFromMatrix(countData = pb, -->
<!--                               colData = meta, -->
<!--                               design = ~ 0 + group) -->
<!-- keep <- rowSums(counts(dds) >= 5) > 5 -->
<!-- dds <- dds[keep,] -->
<!-- dds<-DESeq(dds) -->
<!-- res_5<-results(dds, contrast = c("group","F_Day-5","P_Day-5")) -->
<!-- res_1<-results(dds, contrast = c("group","F_Day-1","P_Day-1")) -->
<!-- saveRDS(agrp, file = here("data/neuron/agrp_neur.RDS")) -->
<!-- ``` -->

<!-- # Filter 24 hr results -->
<!-- ```{r} -->
<!-- res_1<-as.data.frame(res_1) -->
<!-- res_1<-res_1[complete.cases(res_1),] -->
<!-- res_1<-res_1[order(res_1$padj),] -->
<!-- res_1$gene<-rownames(res_1) -->
<!-- write_csv(res_1, path=here("output/neuron/agrp_24hr_dge.csv")) -->
<!-- ``` -->

<!-- # Volcano Plot of DE genes -->
<!-- ```{r volcano plot, fig.width=5, fig.height=5} -->
<!-- res_1 %>% add_rownames("gene") %>% -->
<!--   mutate(siglog=ifelse(padj<0.05&abs(log2FoldChange)>1, yes=T, no=F)) %>%  -->
<!--   mutate(onlysig=ifelse(padj<0.05&abs(log2FoldChange)<1, yes=T, no=F)) %>%  -->
<!--   mutate(onlylog=ifelse(padj>0.05&abs(log2FoldChange)>1, yes=T, no=F)) %>%  -->
<!--   mutate(col=ifelse(siglog==T, yes="1", no =  -->
<!--                       ifelse(onlysig==T, yes="2", no =  -->
<!--                                ifelse(onlylog==T, yes="3", no="4")))) %>%  -->
<!--   mutate(label=ifelse(padj<0.01, yes=gene, no="")) %>% -->
<!--   dplyr::select(gene, log2FoldChange, padj, col, label) -> volc -->

<!-- volc_plot<-ggplot(volc, aes(y=(-log10(padj)), x=log2FoldChange, fill=factor(col), label=label)) +  -->
<!--   xlab(expression(bold(log[2]*~Fold*~Change))) + ylab(expression(bold(-log[10]~pvalue)))+ -->
<!--   geom_point(shape=21, size=3, alpha=0.75) +  -->
<!--   geom_hline(yintercept = -log10(0.05), linetype="dashed") +  -->
<!--   geom_vline(xintercept = c(-1,1), linetype="dashed") + geom_text_repel()  +  -->
<!--   scale_fill_manual(values = c("1" = "red", "2" = "blue", "3" = "darkgreen", "4" = "grey")) + -->
<!--   ggpubr::theme_pubr() + -->
<!--   theme(legend.position = "none") +  -->
<!--   theme_figure -->
<!-- volc_plot  -->
<!-- ``` -->

<!-- # GO Term Analysis -->
<!-- ```{r} -->
<!-- resgo<-res_1[res_1$padj<0.1,] -->
<!-- ego<-gprofiler(rownames(resgo), organism = "mmusculus", significant = T, custom_bg = rownames(dds), -->
<!--                            src_filter = c("GO:BP","REAC","KEGG"),hier_filtering = "strong", -->
<!--                            min_isect_size = 3,  -->
<!--                            sort_by_structure = T,exclude_iea = T,  -->
<!--                            min_set_size = 10, max_set_size = 300,correction_method = "fdr") -->

<!-- write_csv(ego, path=here("output/neuron/agrp_24hr_goterms.csv")) -->

<!-- ego %>% select(domain, term.name, term.id, p.value, intersection, overlap.size) %>%  -->
<!--   separate(intersection, into = c(paste0("gene", 1:max(ego$overlap.size)), remove=T)) %>%  -->
<!--   melt(id.vars=c("domain", "term.name","term.id", "p.value","overlap.size")) %>% na.omit() %>%  -->
<!--   select(-variable) %>%  -->
<!--   mutate(dir = ifelse(resgo[match(value, toupper(resgo$gene)),"log2FoldChange"] > 0, yes = 1, no = -1)) %>% -->
<!--   group_by(term.name, term.id, p.value) %>%  -->
<!--   summarize(zscore = sum(dir)/sqrt(mean(overlap.size)), overlap.size = mean(overlap.size), domain = unique(domain)) -> ego_plot -->

<!-- goterm_plot <- ggplot(ego_plot, aes(x = zscore, y = -log10(p.value), label=str_wrap(term.name,20))) +  -->
<!--   geom_point(aes(size = overlap.size, fill = domain), shape=21, alpha=0.5) +  -->
<!--   scale_size(range=c(2,10)) + -->
<!--   ylab(expression(bold(-log[10]~pvalue))) + -->
<!--   xlab("z-score") + ggsci::scale_fill_npg() + -->
<!--   geom_vline(xintercept = 0, linetype="dashed", color="red") + -->
<!--   geom_text_repel(data = filter(ego_plot, -log10(p.value)>2), bg.colour="white",  -->
<!--                   force=1, min.segment.length = unit(0, 'lines'), lineheight=0.75, size=4) + xlim(c(-3,3)) + -->
<!--   ggpubr::theme_pubr(legend="none") + coord_cartesian(clip="off") + theme_figure -->
<!-- ``` -->

<!-- #Membrane Potential -->
<!-- ```{r} -->
<!-- readxl::read_xlsx(here("data/mouse_data/fig1/191116_arian_ephys.xlsx"), sheet = 1) %>%  -->
<!--   dplyr::rename(Veh = RMP, `FGF-1` = `FGF-1 10nM`) %>% melt() -> rmp -->
<!-- rmp %>% dplyr::group_by(variable) %>%  -->
<!--   dplyr::summarise(mean = mean(value), sd = sd(value), se = sd/sqrt(length(value))) %>% -->
<!--   ggplot(aes(x=variable, y=mean, fill=variable, color = variable)) + -->
<!--   geom_col(width=1, alpha=0.75, colour="black") + -->
<!--   geom_errorbar(aes(x=variable, ymin = mean-se, ymax=mean+se), width=0.2, position = position_dodge(0.9)) + -->
<!--   geom_jitter(data = rmp, inherit.aes = F, aes(x=variable, y=value, fill=variable),  -->
<!--               alpha=0.5, shape=21, position = position_jitterdodge(.5)) + xlab(NULL) +  -->
<!--   geom_signif(y_position=c(-55), xmin=c(1.2), xmax=c(1.8), -->
<!--               annotation=c("***"), tip_length=0, size = 0.5, textsize = 5, color="black", vjust = 2) + -->
<!--   scale_x_discrete(position = "top") + -->
<!--   ylab("Membrane Potential (mV)") + scale_fill_manual("Treatment", values=c("gray80","gray30")) +  -->
<!--   scale_color_manual("Treatment", values=c("gray80","gray30")) + -->
<!--   coord_cartesian(clip="off") + -->
<!--   ggpubr::theme_pubr(legend="none") + -->
<!--   theme(axis.ticks.x = element_blank()) + -->
<!--   theme_figure -> ephysquant -->
<!-- ephysquant -->
<!-- ``` -->

<!-- #Spontaneous action potentials -->
<!-- ```{r} -->
<!-- readxl::read_xlsx(here("data/mouse_data/fig1/191116_arian_ephys.xlsx"), sheet = 2) %>% melt(id.vars="Time") -> aps -->
<!-- aps$Time <- as.factor(aps$Time) -->
<!-- aps %>% dplyr::group_by(Time) %>%  -->
<!--   dplyr::summarise(mean = mean(value), sd = sd(value), se = sd/sqrt(length(value))) -> aps -->
<!-- rects <- data.frame(start=4.5, end=14.5, group=seq_along(5)) -->

<!-- act_pot<- ggplot(aps, aes(x=Time, y=mean)) +  -->
<!--   geom_bar(stat="identity",colour="black", fill="white", width = 1, size=.75) + -->
<!--   geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2, -->
<!--                  position=position_dodge(.9)) +  -->
<!--   ggpubr::theme_pubr() +  -->
<!--   geom_hline(yintercept=0) + -->
<!--   geom_rect(data=rects, inherit.aes = F, aes(xmin=start, xmax=end, ymin = 0, ymax = 140, group=group),  -->
<!--             color="black", fill="grey", alpha=0.3) + -->
<!--   xlab("Time (m)") + ylab("Number of Spontaneous\n Action Potentials") +  -->
<!--   annotate(geom="text", x=9, y=120, label="FGF-1 10nM", color="black", size=4) + -->
<!--   theme_figure -->
<!-- act_pot -->
<!-- ``` -->

<!-- #Synaptic Channel Blockers -->
<!-- ```{r} -->
<!-- detach("package:here", unload = T) -->
<!-- library(here) -->
<!-- readxl::read_xlsx(here("data/mouse_data/fig1/191116_arian_ephys.xlsx"), sheet = 3) %>% dplyr::select(1:3) %>%  -->
<!--   dplyr::rename(`FGF-1+TTX\n+BICC` = `FGF-1 10nM+TTX+Bicc`) %>% melt() -> scb -->

<!-- scb %>% dplyr::group_by(variable) %>% dplyr::summarise(mean = mean(value), sd = sd(value), se = sd/sqrt(length(value))) %>% -->
<!--   ggplot(aes(x=variable, y=mean, fill=variable, color = variable)) + -->
<!--   geom_col(width=1, alpha=0.75, colour="black") + -->
<!--   geom_errorbar(aes(x=variable, ymin = mean-se, ymax=mean+se), width=0.2, position = position_dodge(0.9)) + -->
<!--   geom_jitter(data = scb, inherit.aes = F, aes(x=variable, y=value, fill=variable),  -->
<!--               alpha=0.5, shape=21, position = position_jitterdodge(.25)) + xlab(NULL) +  -->
<!--   geom_signif(y_position=c(-55), xmin=c(2.2), xmax=c(2.8), -->
<!--               annotation=c("ns"), tip_length=0, size = 0.5, textsize = 5, color="black", vjust = 2) + -->
<!--   scale_x_discrete(position = "top") + -->
<!--   ylab("Membrane Potential (mV)") + scale_fill_manual("Treatment", values=c("gray80","gray60", "gray30")) +  -->
<!--   scale_color_manual("Treatment", values=c("gray80","gray60", "gray30")) + -->
<!--   ggpubr::theme_pubr() + theme_figure + -->
<!--   theme(legend.position = "none", axis.ticks.x = element_blank(), axis.text.x=element_text(angle=45, hjust=-0.1, size=6)) +  -->
<!--   coord_cartesian(clip="off")  -> scbquant -->
<!-- scbquant -->
<!-- ``` -->

<!-- #cFos quantification -->
<!-- ```{r} -->
<!-- readxl::read_xlsx(here("data/mouse_data/fig1/191116_Jenny_cFos.xlsx"), sheet = 1) %>% melt() %>% na.omit %>%  -->
<!--   mutate(variable = fct_relevel(variable, "Veh","FGF1")) -> cfos -->
<!-- cfos %>%  dplyr::group_by(variable) %>% dplyr::summarise(mean = mean(value), sd = sd(value), se = sd/sqrt(length(value))) %>% -->
<!--   ggplot(aes(x=variable, y=mean, fill=variable, color = variable)) + -->
<!--   geom_col(width=1, alpha=0.75, colour="black") + -->
<!--   geom_errorbar(aes(x=variable, ymin = mean-se, ymax=mean+se), width=0.2, position = position_dodge(0.9)) + -->
<!--   geom_jitter(data = cfos, inherit.aes = F, aes(x=variable, y=value, fill=variable),  -->
<!--               alpha=0.5, shape=21, position = position_jitterdodge(.25)) + xlab(NULL) +  -->
<!--   geom_signif(y_position=c(70), xmin=c(1.2), xmax=c(1.8), -->
<!--               annotation=c("*"), tip_length=0, size = 0.5, textsize = 5, color="black") + -->
<!--   ylab("cFos+ GFP-AgRP+") + scale_fill_manual("Treatment", values=c("gray80", "gray30")) +  -->
<!--   scale_color_manual("Treatment", values=c("gray80", "gray30")) + -->
<!--   ggpubr::theme_pubr() + -->
<!--   theme(legend.position = "none", axis.ticks.x = element_blank()) +  -->
<!--   coord_cartesian(clip="off") + theme_figure -> cfos_quant -->
<!-- cfos_quant -->
<!-- ``` -->


<!-- ```{r} -->
<!-- intro <- plot_grid(blank, bg_fi, ncol=1, rel_heights = c(1.5,1), labels="a") -->
<!-- seurclus <- plot_grid(prop_seur_byclus, prop_seur_group, nrow=1, labels=c("b","c")) -->
<!-- top <- plot_grid(intro,seurclus, align = "h", axis="tblr", labels = "auto", nrow=1, rel_widths = c(1,2)) -->
<!-- mid <- plot_grid(prop_neur_byclus, deboxplot, goterm_plot, align="hv", axis="tb", nrow=1,  rel_widths = c(1.1,1,1.1), -->
<!--                  labels = c("d","e","f"), scale = 0.95) -->
<!-- midephys <- plot_grid("", ephysquant, nrow=1, labels = c("g","h"), rel_widths = c(2,1), scale=0.8) -->
<!-- lowephys <- plot_grid(act_pot, scbquant, nrow=1, labels = c("i","j"), rel_widths = c(2,1), scale=0.8) -->
<!-- ephys <- plot_grid(midephys,lowephys, ncol=1, rel_heights = c(1,1.25)) -->
<!-- cfos <- plot_grid("", cfos_quant, nrow=1, labels=c("k","l"), rel_widths = c(3,1), scale=0.8) -->
<!-- bottom <- plot_grid(ephys, cfos, nrow = 1) -->
<!-- fig1 <- plot_grid(top,mid,bottom, ncol=1, rel_heights=c(1,1.25,1.25)) -->
<!-- ggsave(fig1, filename  = here("data/figures/fig1/fig1_arranged.tiff"), width = 12, h=12, compression="lzw") -->
<!-- ``` -->
